
# Build stage for panozosistemas.com.ar
FROM node:22-alpine AS panozosistemas-builder
WORKDIR /app/frontend

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./
RUN npm run build

# Production stage
FROM nginx:1.25-alpine
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=panozosistemas-builder /app/frontend/dist /usr/share/nginx/panozosistemas

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
