server {
    listen 80;
    server_name _;

    client_max_body_size 50m;

    root /usr/share/nginx/panozosistemas;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /media/public/ {
        alias /media/public/;
        expires 30d;
        add_header Access-Control-Allow-Origin *;
    }

    location /media/private/ {
        internal;
        alias /media/private/;
    }

    location /api/ {
        proxy_pass http://panozosistemas-backend:8000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        client_max_body_size 50m;
    }

    location /static/ {
        alias /usr/share/nginx/panozosistemas/static/;
        expires 30d;
    }
}